kind: Service
apiVersion: v1
metadata:
  name: fastapi
  namespace: fastapi
spec:
  selector:
    app: fastapi
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: fastapi
  ports:
    - name: http-lb
      protocol: TCP
      port: 80
      targetPort: 8000          
